jupyterlab:
  image: 631013143897.dkr.ecr.eu-west-2.amazonaws.com/data-science-stack-ecr-repo
  ports:
    - "8888:8888"
  volumes:
    - ./notebooks:/home/jovyan/notebooks/
    - $HOME/.aws/:/home/jovyan/.aws/
  environment:
    - JUPYTER_ENABLE_LAB=yes
    - GRANT_SUDO=yes
  user: root
  entrypoint: jupyter lab --ip='0.0.0.0' --notebook-dir=/home/jovyan/notebooks --config=/home/jovyan/.jupyter/jupyter_notebook_config.py --allow-root
